name: build

on:
  pull_request:
    branches:
      - 'main'
    types: [closed]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v3
              with:
                node-version: '18'
            - name: package install
              run: echo 'npm install'
            - name: run build
              run: echo 'npm run build'
            - name: run test
              run: echo 'npm run test'